### ISSUE TITLE
Should the parsers operate on `char` or `u8`?

### ISSUE THREAD

**Issue by duesee** [duesee/abnf-core#1]
The ABNF crate operates on UTF-8, thus `char` and `str` are used. However, older internet protocols may operate on US-ASCII with binary data extensions. In this case, `u8` would probably make more sense. Maybe provide just both?

**Comment by Stargateur** [comment]
I believe you can use nom trait to make this work for both.

**Comment by Stargateur** [comment]
I working on it

**Comment by duesee** [comment]
Fixed in #17
