### ISSUE TITLE
is_hexdig is not pedantic

### ISSUE THREAD

**Issue by Stargateur** [duesee/abnf-core#12]
https://github.com/duesee/abnf-core/blob/b1fceadad7fb2c454387ba31069126bdc4dca098/src/lib.rs#L42-L44

Currently `is_hexdig` allow for either uppercase or lowercase hex digit but [abnf](https://datatracker.ietf.org/doc/html/rfc5234#appendix-B.1) dictate:

> HEXDIG =  DIGIT / "A" / "B" / "C" / "D" / "E" / "F"

That only allow uppercase. I don't know what to do cause this could make a big breaking to be pedantic, even if we introduce a `is_hexdig_relaxed` like in `complete` module.

**Comment by duesee** [comment]
Hm... I think we should try to stick to the RFC as close as possible and deviate from it only for good reasons. So I would consider `is_hexdig` accepting lowercase alpha characters a mistake. I like the idea to allow this in a `_relaxed` version, though.

**Comment by Stargateur** [comment]
nevermind:

> ABNF strings are case insensitive and the character set for these strings is US-ASCII.

is_hexdig is expected to match "abcdef" too.

I didn't know this rule.

**Comment by duesee** [comment]
Argh, you are right. I knew that strings are case-insensitive in ABNF, but my brain ignored that rule for single-char strings like "A", "B", ... somehow. ABNF can be confusing.
