### ISSUE TITLE
uppercase is a bad idea

### ISSUE THREAD

**Issue by Stargateur** [duesee/abnf-core#6]
Why not follow rust nomenclature ? uppercase function are not a thing.

**Comment by duesee** [comment]
The idea was to mimic the ABNF RFC, but I have no strong opinion on that and even tend myself to rectify that now. I will happily accept a PR!

**Comment by Stargateur** [comment]
yeah I guessed.

To add more point from user point of view, it's rust, and user would probably do `abnf_core::ALPHA` that in rust land is a constant.

I believe it's not necessary to copy this behavior from the RFC.

Will make PR after cause I already done one :p

**Comment by duesee** [comment]
> abnf_core::ALPHA that in rust land is a constant.

That is an excellent point I havn't thought about. Now I totally agree it was a bad idea to "mimic the RFC" :-)
