### ISSUE TITLE
name of the crate

### ISSUE THREAD

**Issue by Stargateur** [duesee/abnf-core#8]
yeah maybe too late ?

I would have name it `nom_abnf`, cause, it's about nom and abnf and I dislike `-` in rust crate name cause it doesn't match code `use abnf_core`.

`abnf` is already take and anyway I really thing nom key word should appear in a crate for nom framework like https://crates.io/search?page=1&per_page=10&q=nom

Possible action, use `nom_abnf` now and give up `abnf-core` ?

**Comment by duesee** [comment]
> I would have name it nom_abnf, cause, it's about nom and abnf and 

Ideally, nom is not exposed in the public API, but only via a feature flag maybe for easy composition with other nom crates?

> I dislike - in rust crate name cause it doesn't match code use abnf_core.

Agree. However, this is so common that I do not mind.

> abnf is already take and

Yes, by me! :-) We could also merge abnf-core with abnf and expose a minimal "abnf-core" via a feature flag in the abnf crate.

> anyway I really thing nom key word should appear in a crate for nom framework like https://crates.io/search?page=1&per_page=10&q=nom

Will add that keyword :+1:

> Possible action, use nom_abnf now and give up abnf-core?

Disagee, see comment above for rational.

**Comment by duesee** [comment]
By the way, the "-core" part reflects that this crate is about ABNFs "Core Rules".

**Comment by Stargateur** [comment]
> Yes, by me! :-) We could also merge abnf-core with abnf and expose a minimal "abnf-core" via a feature flag in the abnf crate.

No, that perfect as a separate crate. my only complain was missing nom but a `nom-abnf-core` is long.
I believe your abnf crate is perfectly named for what it does, I just think this should be name nom_abnf.

> By the way, the "-core" part reflects that this crate is about ABNFs "Core Rules".

Meh, yeah that the core rule of all ABNF grammar, but I think it's implicit the `nom_abnf` is for core rule of abnf. but yeah you get a point and again `nom_abnf_core` is long.

The keyword should be fine.

**Comment by duesee** [comment]
I think it should be okay to merge abnf-core with abnf. The only dependants of abnf-core are crates created by me (https://crates.io/crates/abnf-core/reverse_dependencies).

Which downsides do you see with the merge?

**Comment by Stargateur** [comment]
for example, I did a SIP parser, following the ABNF of SIP, I end up coding your crate to have core rule just utils, I always have in mind to make an abnf crate like this and just find this today, so in my parser I don't need at all a parsing crate that parse a ABNF grammar, I need the rule for make my SIP parser. And so I would not at all think to import abnf, A quick read of the description would get me away from it.

**Comment by Stargateur** [comment]
But I understand better why you name this `abnf-core` cause for you it's something other could use but it's link to your `abnf` crate

**Comment by duesee** [comment]
You said that

> A quick read of the description would get me away from it.

and I find that a compelling argument against a merge right now. Still, I am not sure if this could be addressed by improving the README and exposing multiple features such as `["full", "abnf", "core-rules", " nom"]` in the abnf crate.

But let's keep that name for now.

**Comment by duesee** [comment]
>> anyway I really thing nom key word should appear in a crate for nom framework like https://crates.io/search?page=1&per_page=10&q=nom

> Will add that keyword +1

Ah. I think I misunderstood you. The "nom" keyword is already there (see https://github.com/duesee/abnf-core/blob/main/Cargo.toml#L11)

Will close #9 for now.
